// Copyright (c) Prograda Pty. Ltd.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#include "ContainerProperties.h"

namespace skybolt {

QtPropertyPtr createOptionalQtProperty(const QString& displayName, const QVariant& optionalValue, bool present)
{
	auto property = std::make_shared<QtProperty>();
	property->displayName = displayName;

	OptionalProperty opt;
	opt.present = present;
	opt.property = createQtProperty(/* displayName */ "", QVariant(12.345));

	property->setValue(QVariant::fromValue(opt));

	return property;
}

QtPropertyPtr createVectorQtProperty(const QString& displayName, const std::vector<QVariant>& values, const QVariant& itemDefaultValue)
{
	auto property = std::make_shared<QtProperty>();
	property->displayName = displayName;

	PropertyVector children;
	children.itemDefaultValue = itemDefaultValue;

	for (const auto& value : values)
	{
		QString displayName = {}; // Leave display name empty so it can be automatically generated by the rendering widget
		auto childProperty = createQtProperty(displayName, value);
		children.items.push_back(childProperty);
	}

	property->setValue(QVariant::fromValue(children));
	return property;
}

} // namespace skybolt
